### PR TITLE
Enabled the definition of multiple explicit wing stringers.

### LINKED ISSUE #453: wingStringerType does not contain a uID attribute
The CPACS Schema v2.3 does not define a uID attribute in the wingStringerType. Is this intentional or was the attribute just forgotten? We would like to reference a stringer definition and would need it therefore.

### PR DESCRIPTION
**Pull request by codingpoets**
Closes #453

### CODE REVIEW

**Comment by codingpoets** [comment]
Indeed the wingCellType should use the same stringers definition. i must have missed that. Thank you for checking.
Regarding the names; I assume you refer to the 'stringer' and 'stringerExplicit' node names, correct? Could you explain to me why you think that 'stringerParallel' and 'stringerTapered' are more suitable? Are that common terms for stringer definitions/layouts?

**Comment by sdeinert** [comment]
No, the naming is nothing official. I just thought these names would be more obviously stating the differences between the two definition methods than "stringer" and "explicitStringer".
The "stringer" definition basically always results in stringers that are parallel to each other, therefore "parallelStringer" or "stringerParallel", while the "explicitStringer" definition can yield tapered stringers (hence "taperedStringer" or "stringerTapered").
But this is just a suggestion, the current naming would also work with sufficient explanations in the documentation.

**Comment by codingpoets** [comment]
Ok. I think we could do that, but maybe we should call them 'parallelStringerSet' and 'taperedStringerSet' to highlight that the nodes define multiple stringers and not neccessarily just a single one. What do you think?
In order to merge this we should include a picture illustrating the parameters for the tapered stringer definition. Could you provide that? We need to make sure that everything we add to the schema is properly documented.

**Comment by rmaierl** [comment]
Is this convenient?
[Explicit_Stringer_Aachen_Maierl.pdf](https://github.com/DLR-LY/CPACS/files/1097940/Explicit_Stringer_Aachen_Maierl.pdf)

**Comment by codingpoets** [comment]
Is this PR outdated by #511?

**Comment by rmaierl** [comment]
Yes, we can go on in #511.

**Pull request closed without merging**
