### PR TITLE
Added an option for rib placement to use spar points.

### LINKED ISSUE #497: Clearify definition of etaStart node in wingRibsPositioningType
The definition of the etaStart and etaEnd coordinates seems to leave room for misinterpretation. It should be clearified in the description that the eta coordinate is a coordinate measured in the corresponding componentSegment eta xsi coordinate system.

### LINKED ISSUE #533: Additional Rib positioning @ Spar position
The wing rib start and end positioning need the additional possibility to be defined at spar positionings.
It is crucial for a structural analysis to maintain a connected load-path in the wing structure.

The Value etaStart in the wingRibsPositioningType should be replaced by a choice between etaStart and sparPostionStartUID.

The Value etaEnd in the wingRibsPositioningType should be replaced by a choice between etaEnd and sparPostionEndUID.

Attached you will find a CPACS example and a figure of the structure

[refWing_xml.txt](https://github.com/DLR-LY/CPACS/files/1642840/refWing_xml.txt)

refwing_structure

### PR DESCRIPTION
**Pull request by codingpoets**
Closes #533 
Closes #497

### CODE REVIEW

**Comment by sdeinert** [comment]
Is it stated somewhere that the ribReference value must be set to the respective spar in case the sparPositionStart/sparPositionEnd variant is used? If this is not done, I am not sure what the outcome would be if e.g. the ribReference would be leadingEdge while using sparPositionStart/sparPositionEnd.

**Comment by codingpoets** [comment]
> Is it stated somewhere that the ribReference value must be set to the respective spar in case the sparPositionStart/sparPositionEnd variant is used? If this is not done, I am not sure what the outcome would be if e.g. the ribReference would be leadingEdge while using sparPositionStart/sparPositionEnd.
This is a very good point. The _ribReference_ only makes sense in combination with the _etaStart_ and/or _etaEnd_ nodes. It should not have an effect if both _sparPositionStartUID_ and _sparPositionEndUID_ are used.
Thus I would suggest to move it into each of the choices:

Choice 1 between:
```
<xsd:sequence>`
  <etaStart />
  <ribReferenceStart />
</ xsd:sequence>
<sparPositionStartUID />
```

Choice 2 between:
```
<xsd:sequence>`
  <etaEnd />
  <ribReferenceEnd />
</ xsd:sequence>
<sparPositionEndUID />
```

Do you see any problems with this definition?

**Comment by codingpoets** [comment]
Also we might want to add a _ribStart_ and _ribEnd_ node to the explicit rib definitnion (_wingRibExplicitPositioningType_). This might be needed for cases where we want to position the rib depending on two spars, but continue them towards the leading edge and trailing edge as shown below.

grafik

I would make _ribStart_ and _ribEnd_ optional and take the given point from choice 1 and choice 2 as defaults.

**Comment by sdeinert** [comment]
With the introduction of the etaIsoLine in CPACS 3.0 the ribStart-/ribEndReference seems double. With the current change defining the rib start one would have to specify e.g. 'leadingEdge' as a value for the ribStartReference and a componentSegmentUID for the etaIsoLine of the etaStart. Same goes if you would like to specify the eta on a spar.

Should we extend the etaIsoLine definition to also accept sparUIDs?
In this case we could remove the ribStart-/ribEndReference elements here entirely and only use the referenceUID in the etaIsoLine.

Or are the ribReferences used for anything else?

**Comment by codingpoets** [comment]
Again you are right.
Thank you for pointing this out.
Indeed this information is redundant.
I like your suggestion to allow sparUIDs in the _etaIsoLineType_.
But the _etaIsoLineType_ does not allow "_leadingEdge_" or "_trailingEdge_" as values for the _referenceUID_.
Both are used to add a xsi coordinate to the point and thus define the location properly.
Now I wonder why we should not just use eta-xsi coordinates to define the points.

If I am not mistaken there are currently three options by which we want to be able to specify rib points, which are:

1. sparPositionUID
2. eta-xsi coordinates (mainly with xsi=0 or xsi=1)
3. sparUID + eta coordinate along the spar

From a technical perspective we could use the _etaIsoLineType_ to implement the third option, but I would suggest to introduce a separate type for it.
The intention of the _etaIsoLineType_ is to define a "line" and not a point.
In order to avoid confusion I think we should rather create a new _curvePointType_ with the same nodes as the _etaIsoLineType_ but a different meaning and different options for the _referenceUID_.
The _referenceUID_ of the _curvePointType_ must point to a one-dimensional curve, while the _referenceUID_ of the _etaIsoLine_ must point to a two-dimensional surface.
Thus I would modify the rib definitions for both, rib sets and explicit ribs as follows:

```
<xsd:choice>
    <startEtaXsiPoint>
        <eta />
        <xsi />
        <referenceUID />
    </startEtaXsiPoint>
    <startCurvePoint>
        <eta />
        <referenceUID />
    </startCurvePoint>
    <startSparPositionUID />
</xsd:choice>
```

Analogous for the end point.
Feedback is highly appreciated. :)

**Comment by sdeinert** [comment]
Looks like a good solution for this! That should cover all the cases...
This means startEtaXsiPoint would be of type etaIsoLineType or etaXsiRelHeightPointType?

**Comment by codingpoets** [comment]
> This means startEtaXsiPoint would be of type etaIsoLineType or etaXsiRelHeightPointType?
Since _etaIsoLineType_ is missing the xsi coordinate and I would like to avoid the additioinal _relHeight_ element from _etaXsiRelHeightPointType_ I would create a new etaXsiPointType which is the same as etaXsiRelHeightPointType but without specifying the relative height.
I will start with the implementation and let you know when I am done for you to have a final look at the generated documentation.

**Comment by codingpoets** [comment]
Implementation is done. Could you check the result and comment and/or approve?

**Pull request merged**
